# Details about the site
site_name: "Ready to Research"
site_url: https://www.readytoresearch.com
repo_url: https://github.com/ReadyResearchers/www.readytoresearch.com
# Use any word, such as "Default" to ensure that
# the copyright is rendered in the footer with a new partial
copyright: Default

# Definition of the theme
theme:
  # Use the default theme and then customize it further
  name: material
  # Provide an overrides/ directory that contains a main.html file for customization
  custom_dir: overrides
  # Define the logo for the top left-hand corner of the screen and collapsible menu
  logo: img/main/ready-to-research-logo-inverted.svg
  # Define the favicon that displays in the tab of the browser
  favicon: img/main/ready-to-research-favicon-inverted.png
  # Define the logo for the repository for the top right-hand corner of the screen
  icon:
      repo: fontawesome/brands/github
  # Define the fonts used on the site
  font:
      # The main font used in header, footer, and all body text
      text: IBM Plex Sans
      # The font used in all of the source code samples
      code: IBM Plex Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Enable features that are built-in to material for mkdocs
  features:
      # Create a single-page application with faster loading evident
      # Note that this option prohibits the rendering of mathematics;
      # there was some evidence that this was not the case but now
      # it seems likely that using "instant" does break MathJax rendering
      - navigation.instant
      # Display tabs for main sections at top of page
      - navigation.tabs
      # Automatically expand the navigation for each section
      # Note that this might not be suitable for courses with many assignments
      - navigation.expand
      # Always display the navigation menu even when scrolling
      - navigation.tabs.sticky
      # Offer a "Back to Top" button when person starts scrolling up on page
      - navigation.top
      # Make search suggestions when using project-wide search
      - search.suggest
      # Enable the sharing of searches with an icon in search box after start
      - search.share
      # Highlight search terms that match on the chosen page
      - search.highlight

# Extensions to markdown that provide the feature described above the extension itself
markdown_extensions:
    # Add HTML attributes and CSS classes to markdown elements
    - attr_list
    # Support the inclusion of snippets of HTML or Markdown from other files;
    # note that this extension also enables the chosen abbreviations approach
    - pymdownx.snippets:
    # Display and generate emojis using the standard notation (e.g., ":runner:")
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    # Display mathematics using MathJax
    - pymdownx.arithmatex:
          generic: true
    # Display paragraph markers that exhibit as permalinks for section in a file
    - toc:
        permalink: true
    # Highlight source code
    - codehilite
    - markdown.extensions.codehilite:
        guess_lang: true
    # Admonitions in separate boxes
    - admonition
    # Make admonitions collapsible
    - pymdownx.details
    # Support extra social media icons in the footer
    - extra
    # Display keys with easier-to-read symbols
    - pymdownx.keys
    # Allow jump-to-and-jump back footnotes
    - footnotes
    # Enable source code and admonitions to be tabbed
    - pymdownx.tabbed
    # Provide support for more intelligent emphasis and bolding
    - pymdownx.betterem:
        smart_enable: all
    # Support highlighting of text and super- and sub-scripts
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    # Support inserting special characters with greater ease
    - pymdownx.smartsymbols
    # Support the creation of customizable task lists
    - pymdownx.tasklist:
        custom_checkbox: true

# Install plugins
plugins:
  - search
  # Minify the HTML source code to support faster downloads
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
  # Render a PDF of the site for referencing in right-side box,
  # ensuring that PDF rendering only takes place when the
  # environment variable ENABLE_PDF_EXPORT is set to 1.
  # Example: ENABLE_PDF_EXPORT=1 poetry run mkdocs serve
  # Example: ENABLE_PDF_EXPORT=1 poetry run mkdocs build
  # - with-pdf:
  #     author: "Gregory M. Kapfhammer"
  #     copyright: Copyright &copy; 2021 Gregory M. Kapfhammer
  #     cover: true
  #     cover_subtitle: "Get ready to research!"
  #     cover_logo: ""
  #     output_path: "pdf/ready-to-research.pdf"
  #     enabled_if_env: ENABLE_PDF_EXPORT
  # Provide a site printing feature and add an icon
  # for allowing the download of the site's PDF
  - print-site:
      add_to_navigation: false
      print_page_title: ''
      add_table_of_contents: false
      toc_title: ''
      toc_depth: 1
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: "pdf/ready-to-research.pdf"
      enabled: true

# Add icons and links to the footer
extra:
  social:
    # GitHub organization
    - icon: fontawesome/brands/github
      link: https://github.com/ReadyResearchers
    # GitHub issue tracker
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ReadyResearchers/www.readytoresearch.com/issues
    # GitHub discussions
    - icon: fontawesome/solid/comments
      link: https://github.com/ReadyResearchers/www.readytoresearch.com/discussions
    # Discord server invitation (open publicly)
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X69WenZqaB

# Load the stylesheet that overrides parts of the material for mkdocs theme
extra_css:
  - stylesheets/extra.css

# Load the JavaScript needed to support MathJax rendering inside of site
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree that defines the navigation structure
nav:
  - Home: index.md
  - Course Syllabus: data-science/syllabus.md
  - Course Schedule: data-science/schedule.md
  - Technical Skills:
    - Introduction: technical-skills/introduction-technical-skills.md
    - Using VS Code: technical-skills/using-vscode.md
    - Using Terminal: technical-skills/using-terminal.md
    - Using GitHub: technical-skills/using-git.md
    - Python Programming: technical-skills/python-programming.md
    - Using Markdown: technical-skills/using-markdown.md
    - Using MkDocs: technical-skills/using-mkdocs.md
    - Python Packaging: technical-skills/python-packages.md
  - Research Skills:
    - Introduction: research-skills/introduction-research-skills.md
    - Problem Domains: research-skills/problem-domains.md
    - Knowledge Gaps: research-skills/knowledge-gaps.md
    - Setting Goals: research-skills/setting-goals.md
  - Paper Components:
    - Introduction: paper-components/introduction-paper-components.md
    - Paper Titles: paper-components/paper-titles.md
    - Paper Abstracts: paper-components/paper-abstracts.md
